<template>
  <div>
    <p></p>
    <p></p>
    <p></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">本政策仅适用于郑州数链科技有限公司及其关联公司（以下或称“我们”或“数链科技”）提供的产品和服务及其延伸的功能（以下简称“</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务”），包括</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">应用程序</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">小程序、公众号、视频号、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">官方网站</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、下属子网站等（合成“数链科技平台”）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。有关</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的更多信息，请您访问数链科技官方网站</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（域名：www</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">.</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">shdatalink.com</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">中</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">相关介绍</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">部分。如我们提供的某款产品与/</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">或服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">有单独的隐私政策或相应的用户服务协议当中存在特殊约定，则该产品与/</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">或服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的隐私政策将优先适用；该款产品与/</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">或服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">隐私政策和用户服务协议未涵盖的内容，以本政策内容为准。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">【审慎阅读】引言</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">我们</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">的服务和产品只针对非自然人用户</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">主要是企业及非法人组织提供服务</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">但是用于注册企业用户的账号系使用企业授权人员的手机号码进行注册</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">而且需要对账号进行实名认证</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">我们</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">非常重视</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">注册成为企业用户的账号及对应人员</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">的隐私和个人信息保护。您在使用我们的产品与/或服务时，我们可能会收集和使用</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">企业用户及账号对应个人</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">必要</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息。我们希望通过《</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">数链科技</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">隐私政策》（“本政策”）向您说明我们的业务情形和对应需要收集</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">企业用户及</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">个人信息的类型，以及我们为您提供访问、更新、删除这些信息的途径和保护措施，还有当我们共享、转让、公开披露</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">时需要遵守的规则。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">本政策与您所使用的数链科技服务以及该服务所包括的各种业务功能（以下统称“我们的产品与/或服务”）息息相关，希望您在使用我们的产品与/或服务前仔细阅读并确认您已经充分理解本政策所写明的内容（特别是加粗字体</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">或加下划线</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的内容），并让您可以按照本政策的指引做出您认为适当的选择。本政策中涉及的</span><a
          href="#_%E5%8D%81%E4%B8%80%E3%80%81%E6%9C%AC%E6%94%BF%E7%AD%96%E4%B8%AD%E5%85%B3%E9%94%AE%E8%AF%8D%E5%AE%9A%E4%B9%89"><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">相关术语</span></a><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，我们用简明扼要的表述，以便您更好地理解。</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">需要特别说明的是，本政策仅适用于本政策定义的产品与/或服务。当您使用第三方机构直接向您提供的产品或服务并</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">要求</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">向其提供您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的企业用户或</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">个人信息时，我们建议您在使用之前仔细查看他们的隐私政策，了解他们如何处理您的信息，以便审慎决策。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">目录</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">一、我们如何收集您的信息&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">二、我们如何使用您的信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">三、我们如何委托处理共享、转让、公开披露您的信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">四、&nbsp;我们如何保护您的信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">五、&nbsp;您的权利</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">六</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、本政策如何更新&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">七</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、如何联系我们</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><a></a><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">一、我们如何收集您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们会遵循正当、合法、必要的原则，出于本政策所述的以下目的，收集和使用您在使用产品与/或服务过程中主动提供或因使用产品与/或服务而产生的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，以及从第三方获取您的相关</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">如果我们要将您的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">用于本政策未载明的其它用途，或将基于特定目的收集而来的信息用于其他目的，我们将以合理的方式向您告知，并在使用前再次征得您的同意。</span></u></b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（一）我们如何收集您的信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们会通过如下三种渠道获取您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">1、您直接提供的信息：</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们可能收集并存储您在使用数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务时向我们提供的信息，包括</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您在注册账号时</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">申请产品与/或服务时</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">解决争议或就数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务与我们联系时所提供的信息，以及您在使用我们服务过程中产生的关于您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">线上签约</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">线上</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">交易</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">线上融资</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">和</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">相关</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">活动</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">产生的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">2</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、我们从其他来源取得的信息：</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">在取得您同意的前提下，我们还可能从数链科技关联公司及合作伙伴、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">第三方</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信用机构</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您融资时涉及的金融机构</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">及依法成立并合法留存您的相关信息的第三方机构获取您的相关信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（二）我们收集您的哪些信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">在实现数链科技以下各项业务功能的过程中，我们需要收集您的一些信息，用以向您提供服务、提升我们的服务质量、保障您的账号和资金安全以及符合国家法律法规及监管规定。</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">1、账号注册与登录</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">账号登录服务由郑州数链科技有限公司提供，您需要注册</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">账号。在此过程中，为对您的账号进行验证以实现登录目的，</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">将按照《数链科技隐私政策》的约定收集、存储您的数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">账号名、密码、手机号码</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">用于账号注册与登录的基础账号信息和您自行选择补充提供</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">其他账号信息，请您在使用数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">账号登录功能前仔细阅读</span><a
          href="https://in.m.jd.com/help/app/register_info.html"><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">《数链科技用户<span
          style="font-size: 10.5pt;">服务</span><span style="font-size: 10.5pt;">协议》</span></span></a><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><a
          href="https://in.m.jd.com/help/app/private_policy.html"><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">《隐私<span
          style="font-size: 10.5pt;">保护</span><span style="font-size: 10.5pt;">政策》</span></span></a><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">项下的相关内容。同时，在您使用</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技平台账号</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">登录数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的过程中，为将您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技平台账号</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">与您在数链科技上的操作行为相关联，我们将向数链科技收集您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技平台账号</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息，包括</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">数链科技平台账号</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">名、手机号码、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">关联的企业名称</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，收集这些信息是用于为您提供账号登录服务以及保障您的账号安全，若您不提供上述信息，则您无法正常登录数链科技。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">2、实名认证</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">在您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">使用企业认证</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">电子证书服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">线上交易服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">结算确认</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务时，为了遵守</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">企业用户的授权权限</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，我们需要首先认证您身份的真实性，为此您需要提供您的身份基本信息（</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">姓名、手机号、身份证件号码和有效期限信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">）</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">；</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">在发生法律法规及监管规定的特定情形时，还需要您提供</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">身份证件彩色照片或影印件</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">以供我们核对并留存。若</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">需要</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">通过</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">生物特征识别（面部识别、指纹识别、声纹识别等）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">进一步确认您提供信息的准确性时，我们还需要您提供</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">脸部图像/视频</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、指纹、声音</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。我们会将上述信息提交给合法持有您上述信息的第三方身份验证机构，以便对您所提供信息的准确性进行核对如果您不提供上述信息或您的实名验证未通过，则您无法使用上述服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">3、</span><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">使用数链产品或服务中产生的数据和信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">在您使用数链科技提供的产品或服务过程中</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">会产生电子合同</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">收发货记录</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">相关交易单据</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">交易收付款信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">结算信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">物流轨迹信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">货物验收质数量信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">融资信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">融资合同等您与您的合作方的交易数据</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">您与数链科技推荐的金融机构的融资数据</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">上述数据由您和数链科技共同享有数据的所有权和使用权</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">4、</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">提供客户服务及进行投诉处理</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们的客服系统会使用您的</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">账号信息和</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">企业认证</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。为保证您的账号安全，我们的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">客</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服会使用您的账号信息与您核验您的身份。当您需要我们提供与您交易信息相关的客服时，我们将会查询您的</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">企业认证</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">和相关线上活动信息</span></u></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">。</span></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">此外，我们还会收集您与客服联系时您</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">反馈意见、建议或举报时提供的信息，您参与问卷调查时向我们发送的信息</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。如您不提供前述信息，不影响您使用我们提供的其他服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（三）我们通过第三方主体或使用第三方服务时间接收集您信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、我们可能会在您的授权同意范围内从第三方（我们的合作方）处收集并使用您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息。</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">我们保证严格依照与第三方签订的合同以及相关法律规定处理您的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息，同时请您详细阅读该第三方的隐私政策及用户协议。</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">如您拒绝第三方在提供服务时收集、使用或者传递您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息，将可能导致您无法使用相应的服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、第三方登录：当您使用经授权的第三方帐号（如微信、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">支付宝</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">）登录帐号时，如果您决定绑定</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技平台账号</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，我们会在征得您的同意后，从第三方获取您的相关个人信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">四</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">）征得授权同意的例外</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">依据相关法律法规及国家标准，以下情形中，我们可能会依法收集并使用您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">企业用户及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">个人信息无需征得您的同意：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">1、与国家安全、国防安全直接有关的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">2、与公共安全、公共卫生、重大公共利益直接有关的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">3、与犯罪侦查、起诉、审判和判决执行等直接有关的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">4、出于维护</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">主体或其他个人的生命、财产等重大合法权益但又很难得到您同意的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">5、所收集的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">是个人信息主体自行向社会公众公开的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">6、从合法公开披露的信息中收集的您的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">7、根据您的要求签订和履行合同所必需的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">8、用于维护所提供的产品与/或服务的安全稳定运行所必需的，例如发现、处置服务的故障；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">9、法律法规规定的其他情形。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><a></a><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">二、我们如何使用您的</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、为了遵守国家法律法规及监管要求，以及向您提供服务及提升服务质量，或保障您的账号安全，我们会在以下情形中使用您的信息：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（1）实现本政策“我们收集您的哪些信息”约定的目的。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（2）处理您对数链科技产品与/或服务的申请或反馈请求。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（3）提高、完善和优化数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（4）根据法律法规或监管要求向相关部门进行报告。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（5）邀请您参与我们服务有关的客户调研。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（6）我们通过技术手段对数据进行去标识化处理后，去标识化处理的信息将无法识别主体。</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">请您了解并同意，在此情况下我们有权使用已经去标识化的信息；在不透露您</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">的前提下，我们有权对用户数据库进行分析</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">加工处理</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">并予以商业化的利用。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、当我们展示您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">企业或</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">个人信息时，我们会采用包括内容替换、匿名处理方式对您的信息进行脱敏展示，以保护您的信息安全。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">3、当我们要将您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">用于本政策未载明的其它用途时，或基于特定目的收集而来的信息用于其他目的时，会事先征求您的同意。</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">请您理解，我们向您提供的产品与/或服务将不断更新变化。如果您选择使用本政策中尚未列明的其他产品与/或服务时，在我们收集您的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">前，我们会通过业务协议、页面提示的方式向您详细说明信息收集的目的、方式、范围并征求您的明确同意。若您不同意提供前述信息，您可能无法使用该项服务，但不影响您使用其他服务。</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">三、我们如何委托处理、共享、转让、公开披露您的</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（一）委托处理</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">为了提高效率、降低成本，我们可能会委托关联公司或其他专业服务提供商代表我们来处理信息，例如我们会聘请服务提供商为我们提供基础设施技术服务、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数字证书颁发</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">物流轨迹查询</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">质数量检测服务等第三方服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。对我们委托处理</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息的公司、组织和个人，我们会通过书面协议、现场审计等方式要求其遵守严格的保密义务并采取有效的保密措施，要求其只能在委托范围内处理您的信息，而不得出于其自身利益使用您的信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（二）共享</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">我们不会与数链科技以外的任何公司、组织和个人共享您的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，除非获得您的明确同意或属于“共享、转让、公开披露</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">时事先征得授权同意的例外”。我们可能会向</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">数链科技的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">关联公司</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">等第三方</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">共享您的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，以保障为您提供的服务顺利完成；但我们仅会出于合法、正当、必要、特定、明确的目的共享您的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">，并且只会共享提供服务所必要的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">。该等第三方无权将共享的</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">用于任何其他用途。</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">对我们与之共享信息的公司、组织和个人，我们会与其签署严格的保密协定，要求他们按照我们的协议、本政策要求的保密和安全措施来处理信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">1、业务共享</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（1）为便于我们基于统一的账号体系向您提供服务以及便于您进行统一管理、保障系统和账号安全，您的信息可能会在我们和我们的关联公司之间进行必要共享。但我们只会共享必要的信息，且受本政策中所声明目的的约束；我们的关联公司如要改变信息的处理目的，将再次征求您的授权同意。例如，为了我们的关联公司为向您提供服务而需履行监管对客户身份识别的要求，或为我们与关联公司共同向您提供或推荐服务、产品，或为了协助解决您与我们的关联公司之间就交易产生的纠纷，我们会与关联公司共享您的信息。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（2）某些产品或服务可能由第三方提供或由我们与第三方联合提供（您可以在具体产品/服务协议中查看第三方合作机构的名称），我们必须将您的交易</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、融资</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">有关的必要信息与第三方机构共享来实现您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的完成交易</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">申请融资</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的需求。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">2</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、纠纷处理</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">为了保障您及他人的合法权益，如您与其他用户等第三方发生纠纷时，我们会将您的</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">企业名称</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">个人名称</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、有效证件号码、联系方式</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">等</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">相关内容提供给</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">公安机关、司法机关等机关</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，以便及时解决纠纷，但法律法规明确禁止提供的除外。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">3</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、我们可能会根据法律法规规定，或按政府主管部门的强制性要求，对外共享您的信息。如果我们在此过程中违反法律法规的规定，给您造成损失的，我们将承担因此引起的相应责任。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（三）转让</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们不会将您的信息转让给任何公司、组织和个人，但以下情况除外：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、在获得您的明确同意后，我们会向其他方转让您的信息；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、根据适用的法律法规、法律程序的要求、强制性的行政或司法要求所必须的情况进行提供；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">3、在涉及合并、收购或破产清算时，如涉及到信息转让，我们会在要求新的持有您信息的公司、组织继续受本政策的约束，否则我们将要求该公司、组织重新向您征求授权同意。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（四）公开披露</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们仅会在以下情况下，才会公开披露您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">企业或</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">个人信息：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、获得您的明确同意后，按您明确同意的披露方式披露您所指定的信息；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、在法律、法律程序、诉讼或政府主管部门强制性要求的情况下，我们可能会公开披露您的信息。在符合法律法规的前提下，当我们收到上述披露信息的请求时，我们会要求必须出具与之相应的法律文件，如传票或调查函。我们坚信，对于要求我们提供的信息，应该在法律允许的范围内尽可能保持透明。我们对所有的请求都进行了慎重的审查，以确保其具备合法依据，且仅限于执法部门因特定调查目的且有合法权利获取的数据。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（五）共享、转让、公开披露个人信息时事先征得授权同意的例外</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">根据相关法律法规及国家标准，以下情形中，我们共享、转让、公开披露您的信息不必事先征得您的授权同意：</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">1、与您履行法律法规规定的义务相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">2、与国家安全、国防安全直接相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">3、与公共安全、公共卫生、重大公共利益直接相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">4、与刑事侦查、起诉、审判和判决执行等直接相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">5、出于维护您或其他个人的生命、财产等重大合法权益但又很难得到本人授权同意的；</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">6、您自行向社会公众公开的信息；</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">7、从合法公开披露的信息中收集信息的，如合法的新闻报道、政府信息公开等渠道。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">四</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、我们如何保护您的信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（一）我们保护您</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">的</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息的技术与措施</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们非常重视</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">和数据</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">安全，并采取一切合理可行的措施，保护您的信息：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">1、数据安全技术措施</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们已采用符合业界标准的安全防护措施以及行业内通行的安全技术来防止</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您的信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">遭到未经授权的访问、修改，避免您的信息泄露、损坏或丢失：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">2、为保护</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">您的</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">信息采取的其他安全措施</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们通过建立数据分类分级、数据安全管理规范、安全开发规范来管理规范</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息的存储和使用：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">3、安全事件处置</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（1）互联网环境并非百分之百安全，我们将尽力确保或担保您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息的安全性。如果我们的物理、技术、或管理防护设施遭到破坏，导致信息被非授权访问、公开披露、篡改、或毁坏，导致您的合法权益受损，我们将承担相应的法律责任。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（2）为应对信息泄露、损毁和丢失等可能出现的风险，我们制定了多项制度，明确安全事件、安全漏洞的分类分级标准及相应的处理流程。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（3）一旦发生信息安全事件，我们将按照法律法规的要求，及时向您告知安全事件的基本情况和可能的影响、我们已采取或将要采取的处置措施、您可自主防范和降低风险的建议、对您的补救措施等。我们同时将及时将事件相关情况以邮件、信函、电话、推送通知等方式告知您，难以逐一告知信息主体时，我们会采取合理、有效的方式发布公告。同时，我们还将按照监管部门要求，主动上报信息安全事件的处置情况。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（4）如您发现自己的信息泄密，尤其是您的账号及密码发生泄露，请您立即联络我们，以便我们采取相应措施。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（二）我们如何存储和保存您的信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、我们仅在本政策所述目的所必需期间和法律法规及监管规定的时限内保存您的信息。我们承诺为了保证您的权益，除非法律法规另有规定，您的信息我们将保存至您账号注销之日后的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">三年</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。当您的信息超出我们所保存的期限后，我们会对您的信息进行删除或匿名化处理。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、在您终止使用我们的服务后，我们会停止对您的信息的收集和使用，法律法规或监管部门另有规定的除外。如果我们终止服务或运营，我们将及时停止收集您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息的活动，至少提前三十天通知您，并在终止服务或运营后对您的信息进行删除或匿名化处理。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">五</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、您的权利</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">数链科技非常重视您对信息的关注，按照中国相关的法律、法规、标准，以及其他国家、地区的通行做法，尽全力保障您对自己的信息行使以下权利：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（一）访问您的信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、您有权随时访问您的信息，法律法规规定的例外情况除外。如果您想行使数据访问权，可以通过</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">登录您的账号方式</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">自行访问</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、如果您无法通过</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">登录账号方式</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">访问</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息，您可以随时联络我们</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们将在15个工作日内回复您的访问请求并完成核查与处理。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">3、对于您在使用我们的产品或服务过程中产生的其他信息，只要我们不需要过多投入，我们会向您提供。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（二）更正您的信息</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">当您发现我们处理的关于您的信息有错误时，您有权要求我们作出更正。您可以通过</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">登录您的账号方式</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">提出更正申请。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">如果您无法通过上述</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">方式</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">更正</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">信息，您可以随时联络我们</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们将在15个工作日内回复您的更正请求并完成核查与处理。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">（</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">三</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">）注销您的账户</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><b><u><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">您可以在我们的产品与/或服务中直接申请注销账号或注销您申请的具体服务功能，您可以通过</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">登录账号方式</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">访问</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">相关注销选项</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">完成账户注销，还可以与我们联系，经核实您的注销信息、您的合同履行情况等具体细节后，我们对您的注销账号申请进行处理。</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">六</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、本政策如何更新</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、</span><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">我们的隐私政策可能变更。未经您明确同意，我们不会削减您依据本政策所应享有的权利。我们会在数链科技官方网站上发布对本政策所做的任何变更。</span></u></b><b><u><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></u></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、对于重大变更，我们还会采取如下任一方式及时通知您：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（1）您登录相关客户端软件或使用数链科技服务时进行弹窗提醒；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（2）您更新客户端软件版本时进行弹窗提醒；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（3）您使用数链科技服务时向您推送短消息通知；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（4）在数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">进行公告。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">3、本政策所指的重大变更包括但不限于：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（1）我们的业务和服务模式发生重大变化。如业务功能、处理信息的目的、处理的信息类型、信息的使用方式等；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（2）我们在所有权结构、组织架构等方面发生重大变化。如业务调整、破产并购等引起的所有者变更等；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（3）信息共享、转让或公开披露的主要对象发生变化；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（4）您参与信息处理方面的权利及其行使方式发生重大变化；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（5）我们负责处理信息安全的责任部门、联络方式及投诉渠道发生变化时；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（6）信息安全影响评估报告表明存在高风险时。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">4、为了您能及时接收到通知，建议您在联系方式更新时及时通知我们。如您在本政策更新生效后继续使用我们的服务，即代表您已充分阅读、理解并接受更新后的政策并愿意受更新后的政策约束。我们鼓励您在每次使用我们服务时都查阅本政策。您可以在数链科技网站登录/注册页面中查看本政策。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><a></a><b><span style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">七</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;">、如何联系我们</span></b><b><span
          style="font-family: 微软雅黑;color: rgb(0, 0, 0); font-size: 10.5pt;"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">1、我们设立了信息保护专职部门和信息保护专员，如您对本政策或您信息的相关事宜有任何疑问、意见或建议，可与我们客服部门联系</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">，客服联系方式您可登录数链科技官方网站查询</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">客服部门将会同信息保护专职部门及时答复您。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><!--[if--><span style="font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">2、</span><!--[endif]--><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">一般情况下，我们将在十五个工作日内回复并完成核查与处理。如果您对我们的回复不满意，特别是我们的信息处理行为损害了您的合法权益，您还可以通过以下外部途径寻求解决方案：向有管辖权的法院提起诉讼，或向网信、电信、公安及工商等监管部门进行投诉或举报。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><!--[if--><span style="font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">3、</span><!--[endif]--><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">若发生如下任一情形，按照法律法规要求，</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">我们</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">将无法响应您的请求：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（1）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">与国家安全、国防安全有关的；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（2）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">与公共安全、公共卫生、重大公共利益有关的；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（3）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">与犯罪侦查、起诉、审判和执行判决等有关的；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（4）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">有充分证据表明个人信息主体存在主观恶意或滥用权利的；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（5）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">响应您的请求将导致您或其他个人、组织的合法权益受到严重损害的；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">（6）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;">涉及商业秘密的。<a></a></span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt; color: rgb(0, 0, 0); mso-font-kerning:1.0000pt;"></span></p>
  </div>
</template>
<style scoped>
p {
  text-indent: 24pt;
  font-family: 微软雅黑;
  font-size: 10.5pt;
  line-height: 28px;
  min-height: 12px;
}

a {
  color: #1890ff !important;
}

</style>
