<template>
  <div>
    <p></p>
    <p></p>
    <p></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">本政策仅适用于郑州数链科技有限公司及其关联公司（以下或称“我们”或“数链科技”）提供的产品和服务及其延伸的功能（以下简称“</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">平台</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务”），包括APP、官方网站数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">等</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">。有关</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的更多信息，请您访问数链科技官方网站</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">www</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">.</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">shdatalink.com</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">中</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">相关介绍</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">部分。如我们提供的某款产品与/</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">或服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">有单独的隐私政策或相应的用户服务协议当中存在特殊约定，则该产品与/</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">或服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的隐私政策将优先适用；该款产品与/</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">或服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">隐私政策和用户服务协议未涵盖的内容，以本政策内容为准。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">【审慎阅读】引言</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">我们</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">服务</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">和</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">产品</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">只针对</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">非</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">自然人</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">用户</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">，</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">主要是</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">非法人</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">组织</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">提供</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">服务</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">，</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">但是</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">用于</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">注册</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">用户的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">账号</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">系</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">使用企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">授权</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">人员</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">手机</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">号码</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">进行</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">注册</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">，</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">而且需要</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">对</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">账号</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">进行</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">实名</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">认证</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">我们</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">非常重视</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">注册</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">成为</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">用户</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">账号</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">对应</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">人员</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的隐私和个人信息保护。您在使用我们的产品与/或服务时，我们可能会收集和使用</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业用户</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">账号</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">对应</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">必要</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息。我们希望通过《</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数链科技</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">隐私政策》（“本政策”）向您说明我们的业务情形和对应需要收集</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">用户</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息的类型，以及我们为您提供访问、更新、删除这些信息的途径和保护措施，还有当我们共享、转让、公开披露</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及个人</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息时需要遵守的规则。本政策与您所使用的数链科技服务以及该服务所包括的各种业务功能（以下统称“我们的产品与/或服务”）息息相关，希望您在使用我们的产品与/或服务前仔细阅读并确认您已经充分理解本政策所写明的内容（特别是加粗字体</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">或加下划线</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的内容），并让您可以按照本政策的指引做出您认为适当的选择。本政策中涉及的</span></u></b><a
          href="#_%E5%8D%81%E4%B8%80%E3%80%81%E6%9C%AC%E6%94%BF%E7%AD%96%E4%B8%AD%E5%85%B3%E9%94%AE%E8%AF%8D%E5%AE%9A%E4%B9%89"><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">相关术语</span></u></b></a><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">，我们用简明扼要的表述，以便您更好地理解。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">需要特别说明的是，本政策仅适用于本政策定义的产品与/或服务。当您使用第三方机构直接向您提供的产品或服务并</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">要求</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">向其提供您</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">用户</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">或</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息时，我们建议您在使用之前仔细查看他们的隐私政策，了解他们如何处理您的信息，以便审慎决策。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">目录</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">一、我们如何收集您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">二、我们如何使用您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">三、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们如何委托处理共享、转让、公开披露您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">四、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们如何保护您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">五、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">您的权利</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">六</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、本政策如何更新&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">七</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、如何联系我们</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><a></a><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">一、我们如何收集您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们会遵循正当、合法、必要的原则，出于本政策所述的以下目的，收集和使用您在使用产品与/或服务过程中主动提供或因使用产品与/或服务而产生的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息，以及从第三方获取您的相关</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息。</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">如果我们要将您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息用于本政策未载明的其它用途，或将基于特定目的收集而来的信息用于其他目的，我们将以合理的方式向您告知，并在使用前再次征得您的同意。</span></u></b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（一）我们如何收集您的信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们会通过如下三种渠道获取您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">1、您直接提供的信息：</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们可能收集并存储您在使用数链科技服务时向我们提供的信息，包括</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">在注册</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">账号</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">时</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">申请产品与/或服务时</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">解决争议或就数链科技服务与我们联系时所提供的信息，以及您在使用我们服务过程中产生的关于您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">线上</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">签约</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">线上</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">交易</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">线上</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">融资</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">和</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">相关</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">活动</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">产生</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">2</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、我们从其他来源取得的信息：</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">在取得您同意的前提下，我们还可能从数链科技关联公司及合作伙伴、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">第三方</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信用机构</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">您融资</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">时</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">涉及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">金融</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">机构</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">及依法成立并合法留存您的相关信息的第三方机构获取您的相关信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（二）我们收集您的哪些信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">在实现数链科技以下各项业务功能的过程中，我们需要收集您的一些信息，用以向您提供服务、提升我们的服务质量、保障您的账号和资金安全以及符合国家法律法规及监管规定。</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">1、账号注册与登录</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">数链科技中的账号登录服务由郑州数链科技有限公司（以下简称“</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">”）提供，您需要注册数链科技账号登录数链科技。在此过程中，为对您的账号进行验证以实现登录目的，</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">数链科技</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">将按照《数链科技隐私政策》的约定收集、存储您的数链科技</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">账号名、密码、手机号码</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">用于账号注册与登录的基础账号信息和您自行选择补充提供</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">其他账号信息，请您在使用数链科技账号登录功能前仔细阅读</span><a
          href="https://in.m.jd.com/help/app/register_info.html"><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">《数链科技用户<span
          style="font-size: 10.5pt;">服务</span><span style="font-size: 10.5pt;">协议》</span></span></a><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><a
          href="https://in.m.jd.com/help/app/private_policy.html"><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">《数链科技隐私政策》</span></a><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">项下的相关内容。同时，在您使用数链科技账号登录数链科技的过程中，为将您的数链科技账号与您在数链科技上的操作行为相关联，我们将向数链科技收集您的数链科技账号信息，包括</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数链科技账号名、手机号码、</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">关联的企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">名称</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">，收集这些信息是用于为您提供账号登录服务以及保障您的账号安全，若您不提供上述信息，则您无法正常登录数链科技。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">2、实名认证</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">在您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">使用</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">认证</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">电子</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">证书</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">线上</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">交易</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">结算</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">确认</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务时，为了遵守</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">用户</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的授权</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">权限</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">，我们需要首先认证您身份的真实性，为此您需要提供您的身份基本信息（</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">姓名</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、手机号、身份证件</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">号码和有效期限信息</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">）</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">；</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">在发生法律法规及监管规定的特定情形时，还需要您提供</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">身份证件彩色照片或影印件</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">以供我们核对并留存。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">若通过刷脸进一步确认您提供信息的准确性时，我们还需要您提供</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">脸部图像/视频</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">。我们会将上述信息提交给合法持有您上述信息的第三方身份验证机构，以便对您所提供信息的准确性进行核对如果您不提供上述信息或您的实名验证未通过，则您无法使用上述服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">3、</span><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">使用</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数链</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">产品</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">或</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">服务</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">中</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">产生的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数据</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">和</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">在</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">您</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">使用</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数链科技</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">提供</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">产品或</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">服务</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">过程中</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">，</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">会</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">产生</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">电子</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">合同</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">收发货</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">记录</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">相关</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">交易</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">单据</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">交易</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">收付款</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">结算</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">物流轨迹</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">货物</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">验收</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">质数量</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">融资</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">融资</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">合同</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">等</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">您</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">与您的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">合作</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">方</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">交易</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数据</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">您与</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数链</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">科技</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">推荐的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">金融</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">机构</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">融资</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数据</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">，</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">上述</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数据</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">由</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">您和</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数链科技</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">共同</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">享有</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">数据的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">所有权</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">和</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">使用权</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">。</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">4、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">提供客户服务及进行投诉处理</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们的客服系统会使用您的</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">账号信息和</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">认证</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">。为保证您的账号安全，我们的呼叫中心客服和在线客服会使用您的账号信息与您核验您的身份。当您需要我们提供与您交易信息相关的客服与售后服务时，我们将会查询您的</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">认证</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">和相关</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">线上</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">活动</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息</span></u></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">。</span></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">此外，我们还会收集您与客服联系时您</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">反馈意见、建议或举报时提供的信息，您参与问卷调查时向我们发送的信息</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">。如您不提供前述信息，不影响您使用我们提供的其他服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（三）我们通过第三方主体或使用第三方服务时间接收集您信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">1、我们可能会在您的授权同意范围内从第三方（我们的合作方）处收集并使用您的个人信息。</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">我们保证严格依照与第三方签订的合同以及相关法律规定处理您的个人信息，同时请您详细阅读该第三方的隐私政策及用户协议。</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">如您拒绝第三方在提供服务时收集、使用或者传递您的个人信息，将可能导致您无法使用相应的服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">2、第三方登录：当您使用经授权的第三方帐号（如</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">微信、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">支付宝</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">）登录帐号时，如果您决定绑定数链科技账号，我们会在征得您的同意后，从第三方获取您的相关个人信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">四</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">）征得授权同意的例外</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">依据相关法律法规及国家标准，以下情形中，我们可能会依法收集并使用您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">用户及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息无需征得您的同意：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">1、与国家安全、国防安全直接有关的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">2、与公共安全、公共卫生、重大公共利益直接有关的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">3、与犯罪侦查、起诉、审判和判决执行等直接有关的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">4、出于维护</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息主体或其他个人的生命、财产等重大合法权益但又很难得到您</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">同意的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">5、所收集的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息是个人信息主体自行向社会公众公开的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">6、从合法公开披露的信息中收集的您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">7、根据您的要求签订和履行合同所必需的；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">8、用于维护所提供的产品与/或服务的安全稳定运行所必需的，例如发现、处置服务的故障；&nbsp;</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">9、法律法规规定的其他情形。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><a></a><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">二、我们如何使用您的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">1、为了遵守国家法律法规及监管要求，以及向您提供服务及提升服务质量，或保障您的账号</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">安全，我们会在以下情形中使用您的信息：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（1）实现本政策“我们收集您的哪些信息”约定的目的。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（2）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">处理您对数链科技产品与/或服务的申请或反馈请求</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（3）为了使您知晓使用我们服务的状态，我们会向您发送服务提醒。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（4）根据法律法规或监管要求向相关部门进行报告。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（5）邀请您参与我们服务有关的客户调研。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（6）提高、完善和优化数链科技在线服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（7）</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们通过技术手段对数据进行去标识化处理后，去标识化处理的信息将无法识别主体。</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">请您了解并同意，在此情况下我们有权使用已经去标识化的信息；在不透露您</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息的前提下，我们有权对用户数据库进行分析</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">加工</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">处理</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">并予以商业化的利用。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">2、当我们展示您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">或</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息时，我们会采用包括内容替换、匿名处理方式对您的信息进行脱敏展示，以保护您的信息安全。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">3、当我们要将您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">企业</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">及</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">个人信息用于本政策未载明的其它用途时，或基于特定目的收集而来的信息用于其他目的时，会事先征求您的同意。</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">请您理解，我们向您提供的产品与/或服务将不断更新变化。如果您选择使用本政策中尚未列明的其他产品与/或服务时，在我们收集您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息前，我们会通过业务协议、页面提示的方式向您详细说明信息收集的目的、方式、范围并征求您的明确同意。若您不同意提供前述信息，您可能无法使用该项服务，但不影响您使用其他服务。</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">&nbsp;</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">三、</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">我们如何委托处理、共享、转让、公开披露您的</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（一）委托处理</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">为了提高效率、降低成本，我们可能会委托关联公司或其他专业服务提供商代表我们来处理信息，例如我们会聘请服务提供商为我们提供基础设施技术服务、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">数字</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">证书</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">颁发</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">物流</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">轨迹</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">查询</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">质数量检测服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">等</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">第三方</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">。对我们委托处理</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息的公司、组织和个人，我们会通过书面协议、现场审计等方式要求其遵守严格的保密义务并采取有效的保密措施，要求其只能在委托范围内处理您的信息，而不得出于其自身利益使用您的信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（二）共享</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">我们不会与数链科技以外的任何公司、组织和个人共享您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息，除非获得您的明确同意或属于“共享、转让、公开披露</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息时事先征得授权同意的例外”。我们可能会向关联公司、合作伙伴等第三方共享您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息，以保障为您提供的服务顺利完成；但我们仅会出于合法、正当、必要、特定、明确的目的共享您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息，并且只会共享提供服务所必要的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息。该等第三方无权将共享的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">及</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人信息用于任何其他用途。</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">对我们与之共享</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息的公司、组织和个人，我们会与其签署严格的保密协定，要求他们按照我们的协议、本政策要求的保密和安全措施来处理</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">1、业务共享</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（1）为便于我们基于统一的账号体系向您提供服务以及便于您进行统一管理、保障系统和账号安全，您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息可能会在我们和我们的关联公司之间进行必要共享。但我们只会共享必要的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息，且受本政策中所声明目的的约束；我们的关联公司如要改变</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息的处理目的，将再次征求您的授权同意。例如，为了我们的关联公司为向您提供服务而需履行监管对客户身份识别的要求，或为我们与关联公司共同向您提供或推荐服务、产品，或为了协助解决您与我们的关联公司之间就交易产生的纠纷，我们会与关联公司共享您的信息。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">（2）某些产品或服务可能由第三方提供或由我们与第三方联合提供（您可以在具体产品/服务协议中查看第三方合作机构的名称），我们必须将您的订单信息与交易有关的必要信息与第三方机构共享来实现您向其购买商品或服务</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">、</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">申请</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">融资</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">的需求，并促使其可以完成后续的售后服务。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">2</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、纠纷处理</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">为了保障您及他人的合法权益，如您与其他用户</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">等第三方发生纠纷、投诉或被投诉时，我们会将您的</span><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">企业</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">名称</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">个人</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">名称</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、有效证件号码、联系方式、投诉</span></u></b><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">相关内容提供给消费者权益保护部门及监管机关，以便及时解决投诉纠纷，但法律法规明确禁止提供的除外。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">3</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">、我们可能会根据法律法规规定，或按政府主管部门的强制性要求，对外共享您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息。如果我们在此过程中违反法律法规的规定，给您造成损失的，我们将承担因此引起的相应责任。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（三）转让</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们不会将您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息转让给任何公司、组织和个人，但以下情况除外：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">1、在获得您的明确同意后，我们会向其他方转让您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">2、根据适用的法律法规、法律程序的要求、强制性的行政或司法要求所必须的情况进行提供；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">3、在涉及合并、收购或破产清算时，如涉及到</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息转让，我们会在要求新的持有您</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息的公司、组织继续受本政策的约束，否则我们将要求该公司、组织重新向您征求授权同意。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（四）公开披露</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">我们仅会在以下情况下，才会公开披露您的个人信息：</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">1、获得您的明确同意后，按您明确同意的披露方式披露您所指定的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息；</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><span style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">2、在法律、法律程序、诉讼或政府主管部门强制性要求的情况下，我们可能会公开披露您的</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;">信息。在符合法律法规的前提下，当我们收到上述披露信息的请求时，我们会要求必须出具与之相应的法律文件，如传票或调查函。我们坚信，对于要求我们提供的信息，应该在法律允许的范围内尽可能保持透明。我们对所有的请求都进行了慎重的审查，以确保其具备合法依据，且仅限于执法部门因特定调查目的且有合法权利获取的数据。</span><span
          style="mso-spacerun:'yes';font-family:微软雅黑;color: rgb(0, 0, 0);font-size:10.5000pt;mso-font-kerning:1.0000pt;"></span></p>
      <p><b><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">（五）共享、转让、公开披露个人信息时事先征得授权同意的例外</span></b><b><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">根据相关法律法规及国家标准，以下情形中，我们共享、转让、公开披露您的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息不必事先征得您的授权同意：</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">1、与您履行法律法规规定的义务相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">2、与国家安全、国防安全直接相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">3、与公共安全、公共卫生、重大公共利益直接相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">4、与刑事侦查、起诉、审判和判决执行等直接相关的；</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">5、出于维护您或其他个人的生命、财产等重大合法权益但又很难得到本人授权同意的；</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">6、您自行向社会公众公开的</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息；</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
      <p><b><u><span style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">7、从合法公开披露的信息中收集</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);">信息的，如合法的新闻报道、政府信息公开等渠道。</span></u></b><b><u><span
          style="font-family: 微软雅黑; font-size: 10.5pt;color: rgb(0, 0, 0);"></span></u></b></p>
  </div>
</template>
<style scoped>
p {
  text-indent: 24pt;
  font-family: 微软雅黑;
  font-size: 10.5pt;
  line-height: 28px;
  min-height: 12px;
}

a {
  color: #1890ff !important;
}

</style>
