export default [
  {
    path: "storage/index",
    name: "storageIndex",
    component: () => import("@/v2/center/storage/views/index.vue"),
  },
  {
    nickName: "我的仓储",
    path: "storage/myStorage",
    name: "storageMine",
    component: () => import("@/v2/center/storage/views/index.vue"),
  },
  {
    nickName: "入场登记",
    path: "storage/admission",
    name: "storageAdmission",
    component: () => import("@/v2/center/storage/views/index.vue"),
  },
  {
    nickName: "出场登记",
    path: "storage/exit",
    name: "storageExit",
    component: () => import("@/v2/center/storage/views/Exit.vue"),
  },
  {
    nickName: "出入场登记",
    path: "storage/admissionAndExit",
    name: "storageAdmissionAndExit",
    component: () => import("@/v2/center/storage/views/index.vue"),
  },
  {
    nickName: "库存量",
    path: "storage/inventory",
    name: "storageInventory",
    component: () => import("@/v2/center/storage/views/Inventory.vue"),
  },
  {
    nickName: "入库管理",
    path: "storageCenter/in",
    name: "storageCenterIn",
    component: () => import("@/v2/center/storage/views/in/List.vue"),
  },
  {
    nickName: "编辑入库",
    path: "storageCenter/in/creat",
    name: "storageCenterInCreat",
    component: () => import("@/v2/center/storage/views/in/Creat.vue"),
  },
  {
    nickName: "查看入库",
    path: "storageCenter/in/detail",
    name: "storageCenterInDetail",
    component: () => import("@/v2/center/storage/views/in/Detail.vue"),
  },
  {
    nickName: "出库管理",
    path: "storageCenter/out",
    name: "storageCenterOut",
    component: () => import("@/v2/center/storage/views/out/List.vue"),
  },
  {
    nickName: "编辑出库",
    path: "storageCenter/out/creat",
    name: "storageCenterOutCreat",
    component: () => import("@/v2/center/storage/views/out/Creat.vue"),
  },
  {
    nickName: "查看出库",
    path: "storageCenter/out/Detail",
    name: "storageCenterOutDetail",
    component: () => import("@/v2/center/storage/views/out/Detail.vue"),
  },
  {
    nickName: "出仓单管理",
    path: "storageCenter/out/receipt",
    name: "storageCenterOutReceiptList",
    component: () => import("@/v2/center/storage/views/out/receipt/List.vue"),
  },
  {
    nickName: "新增出仓单",
    path: "storageCenter/out/receipt/create",
    name: "storageCenterOutReceiptCreate",
    component: () => import("@/v2/center/storage/views/out/receipt/Create.vue"),
  },
  {
    nickName: "出仓单详情",
    path: "storageCenter/out/receipt/detail",
    name: "storageCenterOutReceiptDetail",
    component: () => import("@/v2/center/storage/views/out/receipt/Detail.vue"),
  },
  {
    nickName: "出仓单作废",
    path: "storageCenter/out/receipt/void",
    name: "storageCenterOutReceiptVoid",
    component: () => import("@/v2/center/storage/views/out/receipt/Void.vue"),
  },
  {
    nickName: "出仓单完结",
    path: "storageCenter/out/receipt/finish",
    name: "storageCenterOutReceiptFinish",
    component: () => import("@/v2/center/storage/views/out/receipt/Finish.vue"),
  },
  {
    nickName: "出仓单开具审核",
    path: "storageCenter/out/receipt/audit",
    name: "storageCenterOutReceiptAudit",
    component: () => import("@/v2/center/storage/views/out/receipt/Audit.vue"),
  },
  {
    nickName: "出仓单文件预览",
    path: "storageCenter/out/receipt/previewFile",
    name: "storageCenterOutReceiptPreviewFile",
    component: () => import("@/v2/center/storage/views/out/receipt/PreviewFile.vue"),
  },

  // 批次管理需求-start
  {
    nickName: "仓房管理",
    path: "storageCenter/storehouse/list",
    name: "storageCenterStorehouse",
    component: () => import("@/v2/center/storage/views/storehouse/List.vue"),
  },
  {
    nickName: "仓房详情",
    path: "storageCenter/storehouse/detail",
    name: "storageCenterStorehouseDetail",
    component: () => import("@/v2/center/storage/views/storehouse/Detail.vue"),
  },
  {
    nickName: "仓房管理-关联资金方",
    path: "storageCenter/storehouse/relatedFunds",
    name: "storageCenterStorehouse/relatedFunds",
    component: () => import("@/v2/center/storage/views/storehouse/RelatedFunds.vue"),
  },
  {
    nickName: "仓房管理-仓房使用历史查询列表",
    path: "storageCenter/history/list",
    name: "storageCenterStorehouse/historyList",
    component: () => import("@/v2/center/storage/views/storehouse/HistoryList.vue"),
  },
  {
    nickName: "仓房管理-仓房使用历史查询详情",
    path: "storageCenter/history/detail",
    name: "storageCenterStorehouse/historyDetail",
    component: () => import("@/v2/center/storage/views/storehouse/HistoryDetail.vue"),
  },
  {
    nickName: "仓房管理-解除封仓",
    path: "storageCenter/storehouse/openWarehouse",
    name: "storageCenterStorehouseOpenWarehouse",
    component: () => import("@/v2/center/storage/views/storehouse/OpenWarehouse.vue"),
  },
  // 批次管理需求-end

  {
    nickName: "查看入库",
    path: "storageCenter/monitor/in/detail",
    name: "storageCenterMonitorInDetail",
    component: () => import("@/v2/center/storage/views/in/Detail.vue"),
  },
  {
    nickName: "查看出库",
    path: "storageCenter/monitor/out/detail",
    name: "storageCenterMonitorOutDetail",
    component: () => import("@/v2/center/storage/views/out/Detail.vue"),
  },
  {
    nickName: "合同管理",
    path: "storageCenter/contract",
    name: "storageCenterContractList",
    component: () => import("@/v2/center/storage/views/contract/List.vue"),
  },
  {
    nickName: "合同查询",
    path: "storageCenter/contract/detail",
    name: "storageCenterContractDetail",
    component: () => import("@/v2/center/storage/views/contract/Detail.vue"),
  },
  {
    nickName: "合同归档",
    path: "storageCenter/contract/archive",
    name: "storageCenterContractArchive",
    component: () => import("@/v2/center/storage/views/contract/Archive.vue"),
  },
  {
    nickName: "创建合同信息",
    path: "storageCenter/contract/Create",
    name: "storageCenterContractCreate",
    component: () => import("@/v2/center/storage/views/contract/Create.vue"),
  },
  {
    nickName: "商品确认单",
    path: "storageCenter/confirmationSlip",
    name: "storageCenterConfirmationSlipList",
    component: () => import("@/v2/center/storage/views/confirmationSlip/List.vue"),
  },
  {
    nickName: "确认单详情",
    path: "storageCenter/confirmationSlip/detail",
    name: "storageCenterConfirmationSlipDetail",
    component: () => import("@/v2/center/storage/views/confirmationSlip/Detail.vue"),
  },
  {
    nickName: "确认单确认",
    path: "storageCenter/confirmationSlip/confirm",
    name: "storageCenterConfirmationSlipConfirm",
    component: () => import("@/v2/center/storage/views/confirmationSlip/Confirm.vue"),
  },
  {
    nickName: "确认单开具",
    path: "storageCenter/contract/createConfirmationSlip",
    name: "storageCenterContractCreateConfirmationSlip",
    component: () => import("@/v2/center/storage/views/contract/CreateConfirmationSlip.vue"),
  },
  {
    nickName: "预警数据",
    path: "storageCenter/earlywarning/data",
    name: "earlyWarningData",
    component: () => import("@/v2/center/storage/views/earlyWarning/data/List.vue"),
  },
  {
    nickName: "预警数据详情",
    path: "storageCenter/earlywarning/data/detail",
    name: "earlyWarningDataDetail",
    component: () => import("@/v2/center/storage/views/earlyWarning/data/Detail.vue"),
  },
  {
    nickName: "预警数据处理",
    path: "storageCenter/earlywarning/data/dispose",
    name: "earlyWarningDataDispose",
    component: () => import("@/v2/center/storage/views/earlyWarning/data/Dispose.vue"),
  },
  {
    nickName: "预警订阅",
    path: "storageCenter/earlywarning/subscribe",
    name: "earlyWarningSubscribe",
    component: () => import("@/v2/center/storage/views/earlyWarning/subscribe/List.vue"),
  },
  {
    nickName: "预警设置",
    path: "storageCenter/earlywarning/setting",
    name: "earlyWarningSetting",
    component: () => import("@/v2/center/storage/views/earlyWarning/setting/List.vue"),
  },
  {
    nickName: "放还款管理",
    path: "storageCenter/loan/loanList",
    name: "loanList",
    component: () => import("@/v2/center/storage/views/loan/LoanList.vue"),
  },
  {
    nickName: "放款登记选择",
    path: "storageCenter/loan/loanFangList",
    name: "loanFangList",
    component: () => import("@/v2/center/storage/views/loan/LoanFangList.vue"),
  },
  {
    nickName: "放款登记",
    path: "storageCenter/loan/loanFang",
    name: "loanFang",
    component: () => import("@/v2/center/storage/views/loan/LoanFang.vue"),
  },
  {
    nickName: "还款登记",
    path: "storageCenter/loan/loanHuan",
    name: "loanHuan",
    component: () => import("@/v2/center/storage/views/loan/LoanHuan.vue"),
  },
  {
    nickName: "放还款详情",
    path: "storageCenter/loan/loanDetail",
    name: "loanDetail",
    component: () => import("@/v2/center/storage/views/loan/LoanDetail.vue"),
  },
  {
    nickName: "仓房管理-报表管理",
    path: "storageCenter/report/list",
    name: "storageCenterStorehouse/reportList",
    component: () =>
      import("@/v2/center/storage/views/ReportList.vue"),
  },
  {
    nickName: "仓房管理-报表管理编辑",
    path: "storageCenter/report/detail",
    name: "storageCenterStorehouse/reportDetail",
    component: () =>
      import("@/v2/center/storage/views/ReportDetail.vue"),
  },
  {
    nickName: "仓房管理-仓储动态监控",
    path: "storageCenter/report/monitoring",
    name: "storageCenterStorehouse/reportMonitoring",
    component: () =>
      import("@/v2/center/storage/views/ReportMonitoring.vue"),
  },
];
